FROM node:20-alpine

WORKDIR /usr/app

COPY package.json ./  

RUN npm install  

COPY . .  

ARG DATABASE_USER  
ARG DATABASE_PASSWORD  
ARG DATABASE_HOST  
ARG DATABASE_PORT  
ARG DATABASE_NAME  
ARG CA_CERTIFICATE_BASE64  
ARG JWT_SECRET  
ARG JWT_EXPIRATION_TIME  

ENV DATABASE_USER=$DATABASE_USER  
ENV DATABASE_PASSWORD=$DATABASE_PASSWORD  
ENV DATABASE_HOST=$DATABASE_HOST  
ENV DATABASE_PORT=$DATABASE_PORT  
ENV DATABASE_NAME=$DATABASE_NAME  
ENV CA_CERTIFICATE_BASE64=$CA_CERTIFICATE_BASE64  
ENV JWT_SECRET=$JWT_SECRET  
ENV JWT_EXPIRATION_TIME=$JWT_EXPIRATION_TIME  

RUN echo "DATABASE_USER=${DATABASE_USER}" > .env  
RUN echo "DATABASE_PASSWORD=${DATABASE_PASSWORD}" >> .env  
RUN echo "DATABASE_HOST=${DATABASE_HOST}" >> .env  
RUN echo "DATABASE_PORT=${DATABASE_PORT}" >> .env  
RUN echo "DATABASE_NAME=${DATABASE_NAME}" >> .env  
RUN echo "CA_CERTIFICATE_BASE64=${CA_CERTIFICATE_BASE64}" >> .env  
RUN echo "JWT_SECRET=${JWT_SECRET}" >> .env  
RUN echo "JWT_EXPIRATION_TIME=${JWT_EXPIRATION_TIME}" >> .env  

RUN npm i -g pnpm  

RUN pnpm build  

EXPOSE 3000 

CMD ["node", "dist/main"]
